name: model-activities-kedro
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.9

    - uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('src/requirements.txt') }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        
    - name: Run Kedro Pipeline
      env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        kedro run
        
    - name: Create CML report - metrics
      env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |        
        echo "## Data metrics" > report.md
        cat "data/09_tracking/metrics.json/$( cat data/last_version.txt )/metrics.json" >> report.md            

        cml-send-comment report.md
        
    - name: Create CML report - plots
      env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |        
        echo "## Data viz" > report.md
        cml-publish data/08_reporting/feature_importance.png --md >> report.md
        cml-publish data/08_reporting/residuals.png --md >> report.md
        
        echo "# Data accuracy" >> report.md
        dvc plots show -y accurancy data/09_tracking/metrics.json/$( cat data/last_version.txt )/metrics.json
              
        cml-send-comment report.md
